n=int(input("So tien ban dau: "))
k=int(input("So thang gui: "))
T=float(input("Lai suat/thang: "))
m=n*(1+k*T)
# print("Voi so tien ban dau "+str(int(n))+", sau " +
#       str(int(k))+" thang gui"+" lai suat "+str(T)+"/ thang")
# print("Thi so tien nhan duoc cuoi ky la:",m)
print("sau",k,"thang gui",end=", ")
print("lai suat "+str(T)+"/ thang")
print("Thi so tien nhan duoc cuoi ky la:",m)